---
abstract: 'CEFACT unit handling.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CEFACT-Unit
no_index:
  directory:
    - examples
    - inc
    - share
    - t
    - xt
requires:
  Class::Utils: 0.03
  Data::CEFACT::Unit: 0
  File::Share: 0
  IO::File: 0
  List::Util: 1.33
  Mo::utils: 0.21
  Text::CSV_XS: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/CEFACT-Unit/issues
  homepage: https://github.com/michal-josef-spacek/CEFACT-Unit
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/CEFACT-Unit
version: '0.01'
